name: res
dependencies:
  - numpy=1.26.4
  - jupyter=1.0.0
  - scipy=1.13.1
  - tqdm=4.66.5
  - scipy=1.13.1
  - matplotlib=3.9.2
  - pytorch=2.6.0
  - notebook=7.2.2
  - pandas=2.2.3
  - python=3.9.20
  - pip:
      - gurobipy==12.0.3
      - numba==0.60.0
  