name: res
channels:
  - pytorch-nightly
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - numpy=1.26.4
  - numpy-base=1.26.4
  - jupyter=1.0.0
  - scipy=1.13.1
  - tqdm=4.66.5
  - scipy=1.13.1
  - matplotlib=3.9.2
  - pytorch=2.6.0
  - notebook=7.2.2
  - pip:
      - gurobipy==12.0.3
      - numba==0.60.0
  